
services:
  db:
    build: ./database
    container_name: postdb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5431:5432"

  backend:
    build:
      context: ../backend
      dockerfile: ../deploy/backend/Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: postgresql://postgres:123@db:5432/postgres
      FLASK_APP: app.py
      FLASK_ENV: production
      PORT: 3000
      CHROMIUM_PATH: /usr/bin/chromium
    # Sovrascrive il file .env del progetto e usa la rete docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=3000

  frontend:
    build:
      context: ../frontend
      dockerfile: ../deploy/frontend/Dockerfile
    container_name: frontend
    ports:
      - "80:80"
